### ISSUE TITLE
Use with div other than body

### ISSUE THREAD

**Issue by buniden** [neilgee/slicknav-menu#1]
Hi, I'm trying to use this with a div other than the body div and am having problems with the drop down links stacking correctly.  

Is there anything that needs to be added to the stylesheet in this case?

**Comment by neilgee** [comment]
Do you have a link?
If not using the body tag, it is best to assign it to an element which is full width. Then the menu items take 100% full width and stack on top evenly.

**Comment by buniden** [comment]
hi neil,

i'm working locally.  I've got it showing up now full width but it's 
open all the time and the menu items are also open all the time.

i sent a screenshot.

Neil Gee wrote:

**Comment by neilgee** [comment]
It may be a javascript error - any js errors in development tools for the browser

**Comment by buniden** [comment]
It's fine when it's in the body tag though.

**Comment by neilgee** [comment]
See here I moved mine to **.site-inner**  lower on the page  - http://wpbeaches.com/ - you may have a javascript that loads an error after the body taggit hub

**Comment by buniden** [comment]
Thanks neil, i'm getting closer now.

Neil Gee wrote:
